version: "3.1"

services:
  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: ${SONARQUBE_DB_CONNECTION}
      SONAR_JDBC_USERNAME: ${POSTGRES_USER}
      SONAR_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env
    ports:
      - "${SONARQUBE_PORT}:9000"
    networks:
      - sonarqube

  db:
    container_name: db
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - ./.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - sonarqube
networks:
  sonarqube: {}
